import { expect, test } from './test'
import { seededScenario, startEngine } from './cockpit-engine-harness'

test('draft markers restore text and files and discard preserves a held answer', async ({}, testInfo) => {
  const engine = await startEngine({ pendingRequests: true, projectsParity: true })
  engine.setMessage('# Inspection page review\n\nThe main offer is clear. I’ll review the inspection flow and the supporting copy.\n\n## Keep the next step visible\n\nUse a direct call to action and explain what happens after a homeowner requests an inspection.\n')
  const scenario = await seededScenario(testInfo, engine.origin, '# Inspection page\n\nReview the offer and the steps after booking.\n', 'inspection-page.md')
  await scenario.writeSettings({ theme: 'strata-night' })
  try {
    const page = await scenario.launch()
    await scenario.app!.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]!.setContentSize(1440, 1000); BrowserWindow.getAllWindows()[0]!.webContents.setZoomFactor(1) })
    await page.clock.setFixedTime(new Date('2026-09-03T12:02:00Z'))
    await page.addStyleTag({ content: '*, *::before, *::after { animation: none !important; transition: none !important; caret-color: transparent !important; }' })
    await page.evaluate(async () => { await document.fonts.ready })
    await page.getByRole('tablist', { name: 'Document navigation' }).getByRole('tab', { name: 'Projects' }).click()
    await page.getByRole('button', { name: 'Open Second engine thread', exact: true }).click()
    await page.getByRole('textbox', { name: 'Message conversation' }).fill('Second thread draft')
    await page.getByRole('button', { name: 'Open in center', exact: true }).click()
    await page.getByRole('tablist', { name: 'Document navigation' }).getByRole('tab', { name: 'Projects' }).click()
    const secondRow = page.locator('.project-thread[data-thread="t2"]')
    await expect(secondRow.getByRole('img', { name: 'Unsent message draft' })).toBeVisible()
    await page.getByRole('button', { name: 'Open Live engine thread', exact: true }).click()
    const conversation = page.getByRole('region', { name: 'Conversation' })
    if (await conversation.getByRole('button', { name: 'Open in center' }).isVisible()) await conversation.getByRole('button', { name: 'Open in center' }).click()
    await page.getByRole('tablist', { name: 'Document navigation' }).getByRole('tab', { name: 'Projects' }).click()
    const input = conversation.getByRole('textbox', { name: 'Message conversation' })
    await input.fill('Keep the next step visible after the offer.')
    const row = page.locator('.project-thread[data-thread="t1"]')
    await expect(row.getByRole('img', { name: 'Unsent message draft' })).toBeVisible()
    await expect(row.locator('.project-thread-status')).toBeVisible()
    await page.evaluate(() => { document.documentElement.dataset.typing = 'true' })
    await conversation.getByRole('button', { name: 'Approve', exact: true }).click()
    await expect(conversation.getByRole('button', { name: 'Approve', exact: true })).toHaveCount(0)
    await conversation.locator('.conversation-messages').evaluate(el => { el.scrollTop = 0 })
    await page.mouse.move(1300, 980)
    await page.screenshot({ path: testInfo.outputPath('drafts-opened.png') })
    await conversation.getByRole('button', { name: 'Discard message…', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Discard this message draft?' })).toBeVisible()
    await page.mouse.move(1300, 980)
    await page.screenshot({ path: testInfo.outputPath('drafts-discard-benchmark.png') })
    await page.getByRole('button', { name: 'Keep draft', exact: true }).click()
    await conversation.locator('.conversation-attachment-input').setInputFiles({ name: 'reference.md', mimeType: 'text/markdown', buffer: Buffer.from('# Reference\n') })
    await expect(conversation.getByRole('button', { name: 'Remove reference.md', exact: true })).toBeVisible()
    await page.reload()
    await page.addStyleTag({ content: "*, *::before, *::after { animation: none !important; transition: none !important; caret-color: transparent !important; }" })
    await page.evaluate(async () => { await document.fonts.ready })
    await page.getByRole('button', { name: 'Open Live engine thread', exact: true }).click()
    await expect(input).toHaveValue('Keep the next step visible after the offer.')
    await expect(conversation.getByRole('button', { name: 'Remove reference.md', exact: true })).toBeVisible()
    await conversation.getByRole('button', { name: 'Answer question', exact: true }).click()
    const answerDialog = page.getByRole('dialog', { name: 'Answer question', exact: true })
    await answerDialog.getByRole('button', { name: 'Version one', exact: true }).click()
    await answerDialog.getByRole('button', { name: 'Hold answer', exact: true }).click()
    await expect(conversation.getByText('Held answer: Version one', { exact: true })).toBeVisible()
    const heldComment = await page.evaluate(async () => {
      const path = (await window.strata.getState()).activeDocument!.path
      return window.strata.holdDraft(path, { kind: 'comment', quote: 'Inspection', from: 2, to: 12, text: 'Keep this document comment.' })
    })
    const visualId = await page.evaluate(async () => {
      const bytes = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=='), value => value.charCodeAt(0))
      const staged = await window.strata.stageConversationAttachment({ name: 'held.png', mimeType: 'image/png', bytes })
      return window.strata.holdVisualComment({ projectId: 'p1', threadId: 't1', source: { staged: staged.id, name: 'held.png', width: 1, height: 1 }, text: 'Keep this visual comment.', marks: [], strokes: [], adjustments: [], marked: [{ captureId: staged.id, bytes }] })
    })
    await conversation.getByRole('button', { name: 'Discard message…', exact: true }).click()
    const confirm = page.getByRole('dialog', { name: 'Discard this message draft?' })
    await expect(confirm).toBeVisible()
    await page.evaluate(() => { document.documentElement.dataset.typing = 'true' })
    await page.screenshot({ path: testInfo.outputPath('drafts-discard.png') })
    await confirm.getByRole('button', { name: 'Keep draft', exact: true }).click()
    await expect(input).toHaveValue('Keep the next step visible after the offer.')
    await conversation.getByRole('button', { name: 'Discard message…', exact: true }).click()
    await confirm.getByRole('button', { name: 'Discard message', exact: true }).click()
    await expect(input).toHaveValue('')
    await expect(conversation.locator('.conversation-attachment-preview')).toHaveCount(0)
    await expect(row.getByRole('img', { name: 'Unsent message draft' })).toHaveCount(0)
    await expect(secondRow.getByRole('img', { name: 'Unsent message draft' })).toBeVisible()
    await expect(conversation.getByText('Held answer: Version one', { exact: true })).toBeVisible()
    expect(await page.evaluate(async id => (await window.strata.getState()).activeDocument?.drafts.some(draft => draft.id === id), heldComment)).toBe(true)
    expect(await page.evaluate(async id => (await window.strata.getState()).engine.projects.flatMap(project => project.visualComments ?? []).find(comment => comment.id === id)?.draft?.text, visualId)).toBe('Keep this visual comment.')
    expect(engine.commands.filter(command => ['thread.turn.start', 'thread.user-input.respond'].includes(String(command.type)))).toEqual([])
    await page.evaluate(() => { document.documentElement.dataset.typing = 'true' })
    await page.screenshot({ path: testInfo.outputPath('drafts-markers.png') })
  } finally { await scenario.dispose(); await engine.close() }
})

test('sending consumes the draft pen while the working status remains separate', async ({}, testInfo) => {
  const engine = await startEngine({ pendingRequests: false })
  const scenario = await seededScenario(testInfo, engine.origin)
  try {
    const page = await scenario.launch()
    await page.getByRole('tablist', { name: 'Document navigation' }).getByRole('tab', { name: 'Projects' }).click()
    await page.getByRole('button', { name: 'Open Live engine thread', exact: true }).click()
    await page.getByRole('button', { name: 'Open in center', exact: true }).click()
    await page.getByRole('tablist', { name: 'Document navigation' }).getByRole('tab', { name: 'Projects' }).click()
    const row = page.locator('.project-thread[data-thread="t1"]')
    const input = page.getByRole('textbox', { name: 'Message conversation' })
    await input.fill('Continue with this change.')
    await expect(row.getByRole('img', { name: 'Unsent message draft' })).toBeVisible()
    await expect(row.locator('[title="Working"]')).toBeVisible()
    await input.press('Enter')
    await expect.poll(() => engine.commands.filter(command => command.type === 'thread.turn.start').length).toBe(1)
    await expect(input).toHaveValue('')
    await expect(row.getByRole('img', { name: 'Unsent message draft' })).toHaveCount(0)
    await expect(row.locator('[title="Working"]')).toBeVisible()
  } finally { await scenario.dispose(); await engine.close() }
})
