import { expect, test } from './test'
import { mkdir } from 'node:fs/promises'
import { seededScenario, startEngine } from './cockpit-engine-harness'
import { primaryKey } from './harness'

test('new conversation: one click, saved draft, model/account options, first send and streamed title', async ({}, testInfo) => {
  const captures = process.env.STRATAMD_CHAT_CAPTURES ?? testInfo.outputPath('new-conversation')
  const engine = await startEngine({ projectsParity: true })
  const scenario = await seededScenario(testInfo, engine.origin)
  try {
    const page = await scenario.launch()
    await scenario.app!.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(1600, 1000))
    await page.getByRole('tab', { name: 'Projects', exact: true }).click()
    await expect(page.getByRole('button', { name: 'New thread in Second project' })).toBeVisible()
    await page.getByRole('button', { name: 'New thread in Second project' }).click()
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p2')
    await expect(page.getByLabel('Message conversation')).toBeFocused()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    expect(engine.commands.filter((command) => command.type === 'thread.create')).toHaveLength(0)
    await page.getByLabel('Message conversation').fill('A draft worth keeping.')
    await page.getByRole('button', { name: 'New thread in Cockpit project' }).click()
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p1')
    await expect(page.getByLabel('Message conversation')).toHaveValue('')
    await page.getByRole('button', { name: 'New thread in Second project' }).click()
    await expect(page.getByLabel('Message conversation')).toHaveValue('A draft worth keeping.')
    await page.getByLabel('Message conversation').fill('')
    await mkdir(captures, { recursive: true })
    await page.getByLabel('Conversation project').click()
    const projects = page.getByRole('region', { name: 'Projects' })
    await expect(projects.getByRole('button', { name: /^Second project/ })).toHaveAttribute('aria-pressed', 'true')
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/project-picker.png` })
    await projects.getByRole('button', { name: /^Cockpit project/ }).click()
    await expect(projects).toHaveCount(0)
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p1')
    await page.getByRole('button', { name: 'New thread in Second project' }).click()
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p2')
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/empty.png` })
    await page.getByRole('button', { name: 'Choose model and account' }).click()
    await page.getByRole('region', { name: 'Models and accounts' }).getByRole('button', { name: 'Claude', exact: true }).click()
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/models.png` })
    await page.getByRole('button', { name: 'Use Claude Fable 5.1', exact: true }).click()
    await page.getByRole('button', { name: 'Thinking and context' }).click()
    await expect(page.getByRole('region', { name: 'Model options' })).toContainText('1M')
    await page.getByRole('button', { name: 'Max', exact: true }).click()
    await page.getByRole('button', { name: '200k', exact: true }).click()
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/thinking.png` })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Conversation access', exact: true }).click()
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/access.png` })
    await page.getByRole('region', { name: 'Access modes' }).getByRole('button', { name: /^Supervised/ }).click()
    await page.getByLabel('Message conversation').fill('Build a focused conversation flow.')
    await page.getByLabel('Message conversation').press('Enter')
    await expect.poll(() => engine.commands.filter((command) => command.type === 'thread.turn.start').length).toBe(1)
    const created = engine.commands.find((command) => command.type === 'thread.create')!
    expect(created).toMatchObject({ projectId: 'p2', title: 'New thread', modelSelection: { instanceId: 'claude-main', model: 'claude-fable-5-1', options: [{ id: 'effort', value: 'max' }, { id: 'contextWindow', value: '200k' }] } })
    expect(engine.commands.find((command) => command.type === 'thread.turn.start')).toMatchObject({ threadId: created.threadId, message: { text: 'Build a focused conversation flow.', attachments: [] }, runtimeMode: 'approval-required', modelSelection: created.modelSelection })
    await expect(page.locator('.conversation-message.user')).toContainText('Build a focused conversation flow.')
    await page.evaluate(async (id) => window.strata.updateEngineThread(id, { title: 'Focused conversation flow' }), String(created.threadId))
    await expect(page.locator('.conversation-title')).toContainText('Focused conversation flow')
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/sent.png` })
    await page.keyboard.press(primaryKey('Shift+N'))
    await expect(page.getByLabel('Message conversation')).toBeFocused()
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p2')
    await expect(page.getByRole('button', { name: 'Choose model and account' })).toContainText('Fable 5.1')
    await expect(page.getByRole('button', { name: 'Choose model and account' })).not.toContainText('Claude Fable')
    await expect(page.getByRole('button', { name: 'Thinking and context' })).toContainText('Max · 200k')
    await scenario.app!.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(1000, 760))
    await page.getByRole('button', { name: 'Choose model and account' }).click()
    if (process.env.STRATA_CAPTURES || process.env.STRATAMD_CHAT_CAPTURES) await page.screenshot({ path: `${captures}/narrow-models.png` })
    const bounds = await page.locator('.chat-menu').boundingBox()
    const viewport = await page.evaluate(() => ({ width: innerWidth, height: innerHeight }))
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height)
  } finally { await scenario.dispose(); await engine.close() }
})

test('first-send refusal keeps the draft and retries the same thread, including after reload', async ({}, testInfo) => {
  const engine = await startEngine({ projectsParity: true })
  const scenario = await seededScenario(testInfo, engine.origin)
  try {
    const page = await scenario.launch()
    await page.getByRole('tab', { name: 'Projects', exact: true }).click()
    await page.getByRole('button', { name: 'New thread in Second project' }).click()
    await page.getByLabel('Message conversation').fill('Preserve this first message.')
    await page.reload()
    await expect(page.getByLabel('Conversation project')).toHaveAttribute('data-value', 'p2')
    await expect(page.getByLabel('Message conversation')).toHaveValue('Preserve this first message.')
    engine.failNextTurn()
    await page.getByLabel('Message conversation').press('Enter')
    await expect(page.getByRole('alert')).toContainText('refused the command')
    await expect(page.getByLabel('Message conversation')).toHaveValue('Preserve this first message.')
    expect(engine.commands.filter((command) => command.type === 'thread.create')).toHaveLength(1)
    await page.getByLabel('Message conversation').press('Enter')
    await expect.poll(() => engine.commands.filter((command) => command.type === 'thread.turn.start').length).toBe(1)
    await expect(page.locator('.conversation-message.user')).toHaveCount(1)
    expect(engine.commands.filter((command) => command.type === 'thread.create')).toHaveLength(1)
  } finally { await scenario.dispose(); await engine.close() }
})

test('an empty workspace opens a focused draft from the keyboard without creating a thread', async ({}, testInfo) => {
  const engine = await startEngine()
  const scenario = await seededScenario(testInfo, engine.origin)
  try {
    const page = await scenario.launchEmpty()
    await expect(page.getByRole('button', { name: 'New thread in Cockpit project' })).toBeVisible()
    await page.keyboard.press(primaryKey('Shift+N'))
    await expect(page.getByRole('region', { name: 'New conversation' })).toBeVisible()
    await expect(page.getByLabel('Message conversation')).toBeFocused()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.locator('.topbar .send-button')).toBeHidden()
    expect(engine.commands.some((command) => command.type === 'thread.create')).toBe(false)
  } finally { await scenario.dispose(); await engine.close() }
})
